### ISSUE TITLE
Add Projects in addition to Affiliations for participants

### ISSUE THREAD

**Issue by yarikoptic** [uwescience/2024-open-source-standards-report#21]
Would that be possible? 
It would help visitors (and participants) to better navigate/appreciate the breadth of involvement there. E.g. I was in particular interested to identify  "Ted Habermann" (AKA Ray E. Habermann) working on/with datacite.

**Comment by arokem** [comment]
Sorry - we're already behind schedule on this.

**Comment by yarikoptic** [comment]
are you seeking contributions?

**Comment by arokem** [comment]
We were (see emails from Anshul in June), but the timeline for that has passed. We are planning to submit the report shortly, but hope to rework this as a journal paper submission and we plan to provide additional opportunities for workshop participants to get involved at that stage.
